include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 100

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_print: error
    - avoid_returning_this
    - avoid_single_cascade_in_expression_statements
    - avoid_types_as_parameter_names
    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - missing_whitespace_between_adjacent_strings
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_if_null_operators
    - prefer_in_for_elements
    - prefer_interpolation_to_compose_strings
    - prefer_is_not_empty
    - prefer_is_not_null
    - prefer_null_aware_operators
    - prefer_single_quotes
    - recursive_getters
    - sized_box_for_whitespace
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_overrides
    - unnecessary_string_interpolations
    - use_build_context_synchronously
    - use_key_in_widget_constructors
    - use_named_constants
    - use_super_parameters
